export default [
    {
        _id: '1',
        type: 'space',
        name: 'Default',
        tabs: []
    },
    // FIXME about: support
    // {
    //     id: '11',
    //     url: 'about://blank',
    //     title: 'blank',
    //     audioPlaying: false,
    //     screenshot: null,
    //     pinned: false,
    // },

    // https://testpages.eviltester.com/styled/index.html#:~:text=Index,-About%20Related%20Sites
    // http://localhost:5173
    {
        _id: '11',
        type: 'tab',
        space: '1',
        url: 'http://localhost:5173',
        title: 'XR',
        screenshot: null,
        pinned: false
    },
    {
        _id: '10',
        type: 'tab',
        space: '1',
        url: 'https://wicg.github.io/controlled-frame',
        title: 'Controlled Frame API',
        favicon: 'https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://wicg.github.io&size=64',
        screenshot: null,
        pinned: false,
    },
    {
        _id: '2',
        type: 'tab',
        url: 'https://open.spotify.com/', 
        title: 'Spotify', 
        space: '1',
        favicon: 'https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://open.spotify.com&size=64',
        screenshot: null,
        pinned: false,
    },
    { 
        _id: '0',
        type: 'tab',
        url: 'http://lanes.localhost/', 
        title: 'Lanes',
        space: '1', 
        favicon: 'https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lanes.pm&size=64',
        screenshot: null,
        pinned: false,
    },
    { 
        _id: '1d',
        type: 'tab',
        space: '1',
        url: 'https://operaneon.com/', 
        title: 'Opera Neon', 
        favicon: 'https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://operaneon.com&size=64',
        screenshot: null,
        pinned: false,
    },
    {
        _id: '3',
        type: 'tab',
        space: '1',
        url: 'https://google.com', 
        title: 'Google', 
        favicon: 'https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://google.com&size=64',
        screenshot: null,
        pinned: false,
    },

    {
        _id: '5',
        type: 'tab',
        space: '1',
        url: 'https://github.com/orgs/Agent54', 
        title: 'Agent54', 
        favicon: 'https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://github.com&size=64',
        screenshot: null,
        pinned: false,
    },
    {
        _id: '16',
        type: 'tab',
        space: '1',
        url: 'https://agregore.org', 
        title: 'Agregore', 
        favicon: 'https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://agregore.org&size=64',
        screenshot: null,
        pinned: false,
    },
    {
        _id: '26',
        type: 'tab',
        space: '1',
        url: 'https://users-and-agents.com', 
        title: 'Agents & Agents', 
        favicon: 'https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://github.com&size=64',
        screenshot: null,
        pinned: false,
    },
    {
        _id: '36',
        type: 'tab',
        space: '1',
        url: 'https://badssl.com/', 
        title: 'Bad SSL', 
        favicon: 'https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://badssl.com&size=64',
        screenshot: null,
        pinned: false,
    },
    {
        _id: '7',
        type: 'tab',
        space: '1',
        url: 'https://www.figma.com/design/HP40QZCsYVBnYahP4oUa2q/Darc-browser?node-id=0-1&p=f&t=mEPREy5GwjSdFBX9-0', 
        title: 'Figma', 
        favicon: 'https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://figma.com&size=64',
        screenshot: null,
        pinned: false,
    }
]
