name: Checks

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build lint image with cache
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: darc-lint:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max,ignore-error=true

      - name: Build lint image without cache
        if: github.event.pull_request.head.repo.full_name != github.repository
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: darc-lint:ci

      - name: Run lint in container
        run: docker run --rm darc-lint:ci pnpm lint
